### ISSUE TITLE
sudo segfaults

### ISSUE THREAD

**Issue by Maescool** [Yubico/yubico-pam#49] opened 2015-01-13 17:02 UTC
I'm able to use my yubikey for logins, that works,
but when trying to apply it on sudo.. it segfaults
this is in my pam.d/common-auth:
`auth sufficient pam_yubico.so id=16 authfile=/etc/yubikey_mappings`
```
pieter@Sesam:~$ sudo su -
[pam_yubico.c:parse_cfg(764)] called.
[pam_yubico.c:parse_cfg(765)] flags 32768 argc 3
[pam_yubico.c:parse_cfg(767)] argv[0]=id=16
[pam_yubico.c:parse_cfg(767)] argv[1]=authfile=/etc/yubikey_mappings
[pam_yubico.c:parse_cfg(767)] argv[2]=debug
[pam_yubico.c:parse_cfg(768)] id=16
[pam_yubico.c:parse_cfg(769)] key=(null)
[pam_yubico.c:parse_cfg(770)] debug=1
[pam_yubico.c:parse_cfg(771)] alwaysok=0
[pam_yubico.c:parse_cfg(772)] verbose_otp=0
[pam_yubico.c:parse_cfg(773)] try_first_pass=0
[pam_yubico.c:parse_cfg(774)] use_first_pass=0
[pam_yubico.c:parse_cfg(775)] authfile=/etc/yubikey_mappings
[pam_yubico.c:parse_cfg(776)] ldapserver=(null)
[pam_yubico.c:parse_cfg(777)] ldap_uri=(null)
[pam_yubico.c:parse_cfg(778)] ldapdn=(null)
[pam_yubico.c:parse_cfg(779)] user_attr=(null)
[pam_yubico.c:parse_cfg(780)] yubi_attr=(null)
[pam_yubico.c:parse_cfg(781)] yubi_attr_prefix=(null)
[pam_yubico.c:parse_cfg(782)] url=(null)
[pam_yubico.c:parse_cfg(783)] urllist=(null)
[pam_yubico.c:parse_cfg(784)] capath=(null)
[pam_yubico.c:parse_cfg(785)] token_id_length=12
[pam_yubico.c:parse_cfg(786)] mode=client
[pam_yubico.c:parse_cfg(787)] chalresp_path=(null)
[pam_yubico.c:pam_sm_authenticate(830)] get user returned: pieter
YubiKey for `pieter': 
[pam_yubico.c:pam_sm_authenticate(972)] conv returned 44 bytes
[pam_yubico.c:pam_sm_authenticate(990)] Skipping first 0 bytes. Length is 44, token_id set to 12 and token OTP always 32.
[pam_yubico.c:pam_sm_authenticate(997)] OTP: [REDACTED] ID: [REDACTED] 
Segmentation fault (core dumped)
```
The redacted part is correct

Using Ubuntu 14.04 64bit
using this PPA:
```
deb http://ppa.launchpad.net/yubico/stable/ubuntu trusty main
deb-src http://ppa.launchpad.net/yubico/stable/ubuntu trusty main
```
Version:
`2.17-1~ppa2~trusty1`

**Comment by klali** [comment] 2015-01-14 08:15
This seems to be a duplicate of #31

**Closed by klali** 2015-01-14 08:15 UTC
